[build]
base = "anoneko-adopt-front/"
ignore = "echo 'Running ignore command...'; git diff $CACHED_COMMIT_REF $COMMIT_REF anoneko-adopt-front; echo 'Git diff exit code: $?'; test $? -eq 1"
command = "npm run build"
publish = "build"

