apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.annotations.clusterIssuer }}
    kubernetes.io/ingress.class: {{ .Values.ingress.annotations.ingressClass }}
  labels:
    app: {{ .Values.selector.app }}
  name: {{ .Values.ingress.name }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.selector.app }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - hosts:
        - {{ .Values.ingress.tlsHost }}
      secretName: {{ .Values.ingress.secretName }}