replicaCount: 2

image:
  repository: sudiptob2/anoneko-adopt
  pullPolicy: Always
  tag: "main"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

selector:
  app: anoneko-adopt-api

ingress:
  name: anoneko-tls-ingress
  host: '"dev.anoneko.sudiptobaral.com"'
  tlsHost: dev.anoneko.sudiptobaral.com
  secretName:  new-dev-tls
  annotations:
    clusterIssuer: letsencrypt-production
    ingressClass: traefik