name: API dev

on:
  push:
#    branches: [ "main" ]
#    paths:
#      - 'anoneko-adopt-api/**'

env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: docker.io

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:anoneko-adopt-api"
          file: "docker/dev/Dockerfile"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print and debug digest
        run: |
          echo ${{ steps.build-and-push.outputs.digest }}
      - name: Update tag in values.yaml
        uses: mikefarah/yq@v4.12.2
        with:
          cmd: yq eval '.image.tag = "${{ steps.build-and-push.outputs.digest }}"' -i anoneko-adopt-api/chart/values.yaml

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create new branch
        run: |
          git checkout -b update-values-${{ github.run_id }}

      - name: Commit and push changes
        run: |
          git add anoneko-adopt-api/chart/values.yaml
          git commit -m "Update image tag in values.yaml"
          git push origin update-values-${{ github.run_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update image tag in values.yaml for ArgoCD deployment"
          body: "This PR updates the image tag in `values.yaml`."
          branch: update-values-${{ github.run_id }}
          base: main